version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/PHOT 300 – Photographic Vision: Theory & Practice II/site"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/PHOT 331 – Digital Photography I/site"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/PHOT 332 – Digital Photography II/site"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/PHOT 398 – As Seen on Screens: Cyberspace & Image Economy/site"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/PHOT 400 – Advanced Workshop in Photography/site"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Toronto"
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - "*"
